---
title: "Types of Statistical Studies"
author: "STAT 218"
format:
  revealjs:
      theme: simple
      slide-number: true
      chalkboard: true
---




## Today's Quick Summary 

<br>

- Statistical studies help us design research collect, organize, summarize, visualize and analyze data.

- We'll see three of them but there are many more.

  - Surveys  
  - Observational Studies  
  - Randomized Experiments  

##
### But first... Vocabulary

<br>

**Explanatory variable** is one that attempts to explain or is purported to cause (at least partially) differences in a **response variable** (sometimes called an outcome variable).

Explanatory → explains    
Response → responds

Examples of response variables are _cholesterol level_ (after taking a new drug), or _weight loss_ (after a special diet).



##
### Surveys


- are designed to ask questions of a small group of people in the hope of learning something about the entire population.

- are typically used to assess opinions or reactions, e.g., political polling, for a particular group of individuals.


- If they get the data from the entire population, it is called a __census__.

- __Example RQ:__ What percentage of current Cal Poly students are freshmen?



## Observational Studies

::: {style="font-size: 30px"}


- The researcher systematically collects data from subjects as an observer, __without manipulating conditions.__


- They can be used to look for associations between two variables, but __not__ causation.


::: {.callout-important}


- **The Presence Confounding Variables:** Observational studies may lead to misinterpretations due to the presence of confounding variables.

- The context in which data collected is crucial in statistics. It alerts us to potential effects of other factors.

:::
:::

##
### Confounding Variable


- Related to explanatory variable.   
- Affects the response variable.  

- Hard to separate how the explanatory and confounding variables affect the response because

1. Individuals who differ for the explanatory variable also are likely to differ for the confounding variable.
2. Different values of the confounding variable are likely to result in different values of the response variable.



##
### Example of RQ

<br>

Is the residence situation of college students (on-campus, off-campus with parents, off-campus in a house/apt, off-campus Greek, other) related to how much alcohol students consume? 

- How many variables do we have here? Are they quantitative or categorical? Explanatory variable? Response Variable? Confounding Variable?

##
### More on Observational Studies
::: {style="font-size: 30px"}

<br>

They resembles an experiment except that the manipulation occurs naturally rather than being imposed by the experimenter.

A special type of observational study in medical research is called a __case-control study.__

- _The relationship between baldness and heart attacks:_ those who had been admitted to the hospital with a heart attack were the cases, and those who had been admitted for other reasons were the controls. The cases and controls are compared to see how they differ on the variable of interest.

- __Advantage:__ the controls are chosen to try to reduce potential confounding variables.
:::


## Experimental Studies

<br>

::: {style="font-size: 32px"}

__Sinusitis and Antibiotics.__ Researchers studying the effect of antibiotic treatment for acute sinusitis compared to symptomatic treatments ***randomly assigned*** 166 adults diagnosed with acute sinusitis to one of two groups: treatment or control. 

Study participants received either a 10-day course of amoxicillin (an antibiotic) or a placebo similar in appearance and taste. The placebo consisted of symptomatic treatments such as acetaminophen, nasal decongestants, etc. At the end of the 10-day period, patients were asked if they experienced improvement in symptoms.

:::


## Experimental Studies

<br>

- The goal is to show one variable causes or has an effect on the other variable.

- rely on volunteers who are willing to undergo whichever treatment they have been assigned.

## Experimental Studies

::: {style="font-size: 30px"}

<br>

- self-reported improvement in symptoms and group type (experimental/placebo). 


- By **randomly assigning** treatments to the subjects, we can address the issue of confounding that complicates observational studies, thereby expanding the scope of conclusions we can draw from the research.

- **Randomized Experiments as the Pinnacle in Scientific Inquiry:** Randomized experiments are often regarded as the pinnacle in scientific investigation due to their ability to overcome confounding.  
  - However, it's crucial to acknowledge that they are not without their own set of challenges.
:::

## Experimental Studies

<br>

Randomized experiments are generally built on four principles.

1. Controlling  
2. Randomization  
3. Replication   
4. Blocking (will learn on Week 9)


##
### Two sources of unwanted bias

<br>

Those who might influence the results (the subjects, treatment administrators, technicians, etc.)

<br>

Those who evaluate the results (judges, experimenters, etc.)


## 
### Reducing Bias in Experimental Studies

<br>

We can reduce bias in experimental studies by employing:

- Treatment/Control Group  
  - Placebo Group   
  - Blinding / Double Blinding

## Placebo
::: {style="font-size: 32px"}

- Placebos are commonly administered to human subjects in experiments, often in the form of an inert substance like a sugar pill.
  
- The well-documented placebo response illustrates that individuals frequently exhibit positive reactions to any treatment, even when it lacks active ingredients.

- In many cases, a placebo leads to a subtle yet genuine improvement in patients, a phenomenon known as the _placebo effect._

  - However, when implementing a placebo control, it is crucial for subjects to remain unaware of their group assignment—whether they are receiving the active treatment or the inert placebo.
  
:::


## Blinding/Double-Blinding

<br>


- If researchers keep patients unaware of their treatment, the study is termed __blind__.

- When both researchers and patients remain unaware of the individuals in the treatment groups, it is referred to as __double-blind__.

##
### Extra Activity

Decide on what type of study, survey, observational study or experiment?

- Who has more support among “likely voters”?
- Who uses Instagram more: men or women?
- Does smoking during pregnancy increase the risk of having a premature baby?
- Does aspirin prevent heart attacks? 
